### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/odoo-support#30]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] adhoc_modules
- [ ] adhoc_modules_web_support
- [ ] database_tools
- [ ] server_global_parameters
- [ ] server_mode
- [ ] server_mode_fetchmail
- [ ] server_mode_mail
- [ ] support_branding_adhoc
- [ ] web_support_client
- [ ] web_support_client_doc
- [ ] web_support_client_issue
- [ ] website_server_mode

**Comment by SalahAdDin** [comment]
Is `database_tools` working?

**Comment by jjscarafia** [comment]
not yet, not sure if we are going to OCA auto backup module..
