### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/odoo-support#31]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] adhoc_modules
- [ ] adhoc_modules_web_support
- [ ] database_tools
- [ ] server_global_parameters
- [ ] server_mode
- [ ] server_mode_fetchmail
- [ ] server_mode_mail
- [ ] support_branding_adhoc
- [ ] web_support_client
- [ ] web_support_client_doc
- [ ] web_support_client_issue
- [ ] website_server_mode
