### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/odoo-support#53]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] database_tools
- [ ] server_global_parameters
- [ ] server_mode
- [ ] server_mode_fetchmail
- [ ] server_mode_mail
